language: node_js
node_js:
  - '10'
before_install:
  - npm install -g bower
  - sudo chown "$USER:" /opt
  - sudo apt-get update -qq
  - sudo apt-get install -qq make gcc
  - PACKAGE=duktape-2.4.0; ( cd /opt && wget "https://duktape.org/$PACKAGE.tar.xz" && tar xf "$PACKAGE.tar.xz" && make -C "$PACKAGE/" -f Makefile.cmdline DEFINES=-DDUK_CMDLINE_FILEIO && sudo install -Dm755 "$PACKAGE/duk" /usr/local/bin/duk && rm -rf "$PACKAGE.tar.xz" "$PACKAGE/" )
  - PACKAGE=quickjs; VERSION=2020-07-05; ( cd /opt && git clone --bare 'https://gitlab.com/felix.s-git-mirrors/quickjs.git' && git --git-dir=quickjs.git worktree add "$PACKAGE/" "$VERSION" && make -C "$PACKAGE/" qjs && sudo install -Dm755 "$PACKAGE/qjs" /usr/local/bin/qjs && rm -rf "quickjs.git" "$PACKAGE/" )
  - PACKAGE=Rhino1_7R4_RELEASE; wget https://github.com/mozilla/rhino/archive/$PACKAGE.zip && unzip $PACKAGE -d /opt/ && rm $PACKAGE.zip
  - PACKAGE=Rhino1_7R4_RELEASE; echo -e '#!/bin/sh\njava -jar /opt/Rhino1_7R4_RELEASE/js.jar $@' | sudo tee /usr/local/bin/rhino && sudo chmod +x /usr/local/bin/rhino
  - PACKAGE=ringojs-0.9; wget http://ringojs.org/downloads/$PACKAGE.zip && unzip $PACKAGE -d /opt/ && rm $PACKAGE.zip
  - PACKAGE=ringojs-0.9; sudo ln -s /opt/$PACKAGE/bin/ringo /usr/local/bin/ringo && sudo chmod +x /usr/local/bin/ringo
before_deploy:
  - make build
deploy:
  - provider: npm
    email: public@oxy.fi
    api_key:
      secure: c1xVoKfBO4ZGplOkwugeWs9qtC2NQAXLS6ntUAhdk+aeFrxQBMR5oUQ721IM8V9hYhuNv8qJZowoJNyzGNr/43uh9ZSCohddX6OIyVc1Lu84JEQAt1W/WgKF8j0d/p9+WFD3EZOyvf4eotAjamJbsXkGN4GlsD0f2TKOKlt0/YY=
    on:
      tags: true
      all_branches: true
  - provider: releases
    api_key:
      secure: GGN5c5EDpUwBduAiXefBvQjcKH8HKRvMaAHLEIvIm547sR7YUz/vynkNd7uInPG8ZCD73GHxZVxOk335TsHg7XR6Tz+mm3PmyMmqHcCMqSG+hR+s++oCiC2R04q/yM0LsaWlKPr/xzSg6dZynJsW0hy7AinXlK4g4B3kI5wtGls=
    file:
      - dist/luaparse.js
      - dist/luaparse.min.js
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
after_success:
  - '[ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ] && BUILD_DOCS=true || BUILD_DOCS=false'
  - '[ "$BUILD_DOCS" = "true" ] && openssl aes-256-cbc -K $encrypted_ce12c8d20fd6_key -iv $encrypted_ce12c8d20fd6_iv -in .travis/deploy_key.enc -out .travis/deploy_key -d'
  - '[ "$BUILD_DOCS" = "true" ] && chmod 600 .travis/deploy_key && eval `ssh-agent -s` && ssh-add .travis/deploy_key'
  - '[ "$BUILD_DOCS" = "true" ] && git clone --branch gh-pages git@github.com:fstirlitz/luaparse.git gh-pages && cd gh-pages'
  - '[ "$BUILD_DOCS" = "true" ] && make'
  - '[ "$BUILD_DOCS" = "true" ] && git config user.name "Travis" && git config user.email "public@oxy.fi"'
  - '[ "$BUILD_DOCS" = "true" ] && git add . && git commit --message "build documentation" && git push origin gh-pages'
